[package]
name = "string-alloc"
version = "0.0.1"
edition = "2021"
authors = ["Ted Yin <ted@lyquor.xyz>"]
description = "Allocator-aware no-std-compatible String implementation"
license = "Apache-2.0"
readme = "README.md"
